var cookieSession = require('cookie-session')
var express = require('express')

var app = express()

app.set('trust proxy', 1) // trust first proxy

app.use(cookieSession({
  name: 'session',
  keys: ['<Insert Key Found HERE>']
}))

app.get('/', function (req, res, next) {
  // Update views
  req.session.username = 'admin'

  // Write response
  res.end("good luck")
})

app.listen(3000)

//Go check the generated Cookie. When you set a new session value, a new cookie signed cookie is generated by the cookie-session library 
